// Package storage defines the Store interface for secret persistence.
package storage

import (
	"context"
	"time"
)

// Secret represents an encrypted secret stored in the system.
type Secret struct {
	ID            string
	Ciphertext    []byte
	BurnAfterRead bool
	ExpiresAt     time.Time
	CreatedAt     time.Time
	Views         int
	Type          string
}

// CreateParams holds the parameters for creating a new secret.
type CreateParams struct {
	Ciphertext    []byte
	BurnAfterRead bool
	ExpiresAt     time.Time
	Type          string
}

// Store is the persistence interface for secrets.
// All implementations must be safe for concurrent use.
type Store interface {
	// Create stores a new secret and returns its generated ID.
	// The ID is generated by the store implementation (16 random bytes, hex-encoded).
	Create(ctx context.Context, params CreateParams) (id string, err error)

	// Get retrieves a secret by ID.
	// Returns (nil, nil) if the secret does not exist or has expired.
	// If the secret has burnAfterRead=true, the implementation MUST atomically
	// delete the secret and return it in the same operation.
	// Increments the view counter for non-burn secrets.
	Get(ctx context.Context, id string) (*Secret, error)

	// Delete removes a secret by ID. No error if it doesn't exist.
	Delete(ctx context.Context, id string) error

	// Cleanup removes all expired secrets.
	// Returns the number of secrets removed.
	Cleanup(ctx context.Context) (removed int, err error)

	// Stats returns anonymous usage counters.
	Stats(ctx context.Context) (*Stats, error)

	// Close releases all resources.
	Close() error
}

// Stats holds anonymous usage counters — no PII, no secret data.
type Stats struct {
	TotalCreated    int64 `json:"totalCreated"`
	ActiveSecrets   int64 `json:"activeSecrets"`
	BurnedSecrets   int64 `json:"burnedSecrets"`
	ExpiredCleaned  int64 `json:"expiredCleaned"`
}
